<?php 
include "header.php";$_Is_EditMode = !empty($_GET["ref"]);$newsCode = $_Is_EditMode ? $_GET["ref"] : GenerateNextID("news","NewsCode",5,"N");if(isset($_POST["btnSubmit"])){    $txtSubject = $_POST["txtSubject"];    $txtDescription = $_POST["txtDescription"];    $ddlCattegory = $_POST["ddlCattegory"];    $uploadFileTarget = "/_upload_images/".strtolower($_COG_ITEM_CODE)."/";    $fileUploaded = $_FILES["fileUpload"];    if(!empty($fileUploaded["name"])){        $fileUploadedPath = $uploadFileTarget.UploadFile($_FILES["fileUpload"],$uploadFileTarget,$newsCode);    }else{        $fileUploadedPath = $_POST["hddBackUpImage"];    }    if($_Is_EditMode)    {        $sqlUpdate = "update news set                     Subject = '$txtSubject'                    ,Description = '$txtDescription'                    ,Image = '$fileUploadedPath'                    ,UpdatedOn = NOW()                    ,UpdatedBy = '".UserService::UserCode()."'                    ,CategoryCode = '$ddlCattegory'                    where NewsCode = '$newsCode'        ";        ExecuteSQL($sqlUpdate);    }    else    {        $sqlInsert = "insert into news (NewsCode,Subject,Description,Image,Active,CreatedOn,CreatedBy,CategoryCode)                    VALUES(                        '$newsCode',                        '$txtSubject',                        '$txtDescription',                        '$fileUploadedPath',                        '1',                        NOW(),                        '".UserService::UserCode()."',                        '$ddlCattegory'                    );";        ExecuteSQL($sqlInsert);    }    Redirect("news.php");    exit();}if($_Is_EditMode){    $sqlPrd = "select * from news where NewsCode = '$newsCode'";    $data = SelectRow($sqlPrd);}?>
<form method="post" enctype="multipart/form-data" class="container">
    <h5><b>Manage News</b></h5>
    <hr />
    <div class="row">        <div class="col-sm-12">            <label>Subject</label>            <input type="text" placeholder="Subject..." required name="txtSubject" id="txtSubject" value="<?php echo $data["Subject"] ?>" class="form-control input-sm" />        </div>    </div>    <br />    <div class="row">        <div class="col-sm-12">            <label>Category</label>            <select name="ddlCattegory" required class="form-control input-sm">                <option value="">Choose one</option>                <?php                $sqlCate = "select * from news_category                         where Active = 1 ";                if(UserService::_IsAlumni()){                    $sqlCate .= " and AllowAlumni = 1 ";                }                $sqlCate .= " order by CategoryName ";                $datasCate = SelectRows($sqlCate);                $cIndex = 0;                while($dataCate = $datasCate->fetch_array()){                ?>                <option value="<?php echo $dataCate["CategoryCode"] ?>" <?php echo $data["CategoryCode"] == $dataCate["CategoryCode"] ? 'selected="selected"' : '' ?>><?php echo $dataCate["CategoryName"] ?></option>                <?php } ?>            </select>        </div>    </div>    <br />    <div class="row">        <div class="col-sm-12">            <label>Description</label>            <textarea name="txtDescription" id="txtDescription" required rows="10" class="form-control input-sm"><?php echo $data["Description"] ?></textarea>        </div>    </div>
    <br />
    <div class="row">        <div class="col-sm-12">            <label>Picture</label><br />            <input type="file" name="fileUpload" accept="images/*" id="fileUpload" <?php echo $_Is_EditMode ? "" : "required" ?> />            <input type="hidden" name="hddBackUpImage" value="<?php echo $data["Image"] ?>" />        </div>    </div>
    <hr />
    <div>
        <button type="submit" name="btnSubmit" onclick="return confirm('ต้องการบันทึกหรือไม่');" class="btn btn-primary">
            <i class="fa fa-save"></i>Save                   
        </button>
        <a href="news.php" class="btn btn-secondary"><i class="fa fa-remove"></i>Cancel        </a>
    </div>
</form>
<?php 
include "footer.php";
?>